<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:TalendProperties="http://www.talend.org/properties">
  <TalendProperties:Property xmi:id="_HUlkAAhJEeK65urEjR2qTQ" id="_ZRnIoGpPEemKI-93HvLUeQ" label="TDI42239_tLogCatcher_tAssertCatcher1" creationDate="2012-08-21T16:52:11.139+0800" modificationDate="2019-04-29T15:38:16.926+0800" version="0.1" statusCode="" item="_HUlkAghJEeK65urEjR2qTQ" maxInformationLevel="ERROR" displayName="TDI42239_tLogCatcher_tAssertCatcher1">
    <author href="../talend.project#_DE5c4BhgEem82vCEVfCOaw"/>
    <informations xmi:id="_orQhQGpREemKI-93HvLUeQ" level="ERROR" text="Unreachable catch block for TDI42239_tLogCatcher_tAssertCatcher1.TalendException. This exception is never thrown from the try statement body"/>
  </TalendProperties:Property>
  <TalendProperties:ItemState xmi:id="_ZRsBIGpPEemKI-93HvLUeQ" path=""/>
  <TalendProperties:ProcessItem xmi:id="_HUlkAghJEeK65urEjR2qTQ" property="_HUlkAAhJEeK65urEjR2qTQ" state="_ZRsBIGpPEemKI-93HvLUeQ">
    <process href="TDI42239_tLogCatcher_tAssertCatcher1_0.1.item#/"/>
  </TalendProperties:ProcessItem>
</xmi:XMI>
